apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: azure-demo-image
  name: azure-demo-image
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-demo-image
  template:
    metadata:
      labels:
        app: azure-demo-image
    spec:
      containers:
      - name: azure-demo-image
        image: mydemoregistrykk.azurecr.io/azure-demo-image:v1
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: azure-demo-load-balancer
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: azure-demo-image
