apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-demo
  template:
    metadata:
      labels:
        app: azure-demo
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-demo
        image: openjdk:8-jdk-alpine
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: azure-demo
spec:
  ports:
  - port: 8080
